// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ_TgdFflgCB3RX3-TQ60mUujYGyjSk5U',
    appId: '1:62157388112:web:40046920635063667d5455',
    messagingSenderId: '62157388112',
    projectId: 'vishal-49ba6',
    authDomain: 'vishal-49ba6.firebaseapp.com',
    databaseURL: 'https://vishal-49ba6-default-rtdb.firebaseio.com',
    storageBucket: 'vishal-49ba6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ_TgdFflgCB3RX3-TQ60mUujYGyjSk5U',
    appId: '1:62157388112:android:40046920635063667d5455',
    messagingSenderId: '62157388112',
    projectId: 'vishal-49ba6',
    databaseURL: 'https://vishal-49ba6-default-rtdb.firebaseio.com',
    storageBucket: 'vishal-49ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsiWsyO98Rcru5508QPQk-hdwWGm_hCCA',
    appId: '1:62157388112:ios:53e9fa9ebbb1d0077d5455',
    messagingSenderId: '62157388112',
    projectId: 'vishal-49ba6',
    databaseURL: 'https://vishal-49ba6-default-rtdb.firebaseio.com',
    storageBucket: 'vishal-49ba6.firebasestorage.app',
    androidClientId: '62157388112-0lpn83heonqnklolgtn65hncqcsm3ki7.apps.googleusercontent.com',
    iosClientId: '62157388112-18do556sfe8rvjcc31n8f300huicqlsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.strame',
  );
}

























